services:
  web:
    build: .
    container_name: django_app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - .:/app
    # environment:
    #   - DB_NAME=lyvup_db
    #   - DB_USER=amit
    #   - DB_PASSWORD=we2code
    #   - DB_HOST=postgres-db
    ports:
      - "8000:8000"
    # networks:
    #   - app-network
    # depends_on:
    #   db:
    #     condition: service_healthy

#   db:
#     image: postgres:13
#     container_name: postgres-db
#     environment:
#       POSTGRES_DB: lyvup_db
#       POSTGRES_USER: amit
#       POSTGRES_PASSWORD: we2code
#     networks:
#       - app-network
#     # volumes:
#     #   - postgres_data:/var/lib/postgresql/data
#     ports:
#       - '5433:5432'
#     healthcheck:
#       test: [ "CMD-SHELL", "pg_isready -U amit -d lyvup_db" ]
#       interval: 5s
#       timeout: 20s
#       retries: 5

# # volumes:
# #   postgres_data:
# networks:
#   app-network:
#     driver: bridge

# services:
#   web:
#     build: .
#     container_name: django_app
#     environment:
#       - DB_HOST=postgres-db
#       - DB_PORT=5432
#       - DB_NAME=mydb
#       - DB_USER=myuser
#       - DB_PASSWORD=mypassword
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: postgres-db
#     environment:
#       - POSTGRES_DB=mydb
#       - POSTGRES_USER=myuser
#       - POSTGRES_PASSWORD=mypassword
#     ports:
#       - "5433:5432"
